### ISSUE TITLE
SupportMapFragment Error when Refractoring to androidX 

### ISSUE THREAD

**Issue by chlegou** [googlemaps/android-samples#100]
I was facing this error for two days, when i tried to refactor to androidX.

the demo app is working fine, but when i tried to refactor to androidX, it stopped working. the error is here:

```
SupportMapFragment mapFragment =
                (SupportMapFragment) getSupportFragmentManager().findFragmentById(R.id.map);
```

and here is the error message: 

> cannot cast "androidx.fragment.app.Fragment" to "com.google.android.gms.maps.supportmapfragment"

apparently, it's related to android support only. but since i'm working with material, so i require androidX, does google maps have a working solution for that? to make it compatible with?

**Comment by chlegou** [comment]
i have solved the issue by updating google map to the latest version.

**Comment by Sander0542** [comment]
This didnt work for me

**Comment by chlegou** [comment]
@Sander0542 it's the same version i'm using.

according to the official google map documentation, this particular error should be resolved like that in androidX when updating to latest version. try to clean your project and re-build, if didn't solve it, check if there is other errors.

**Comment by Sander0542** [comment]
I found this on the Google Issue Tracker

https://issuetracker.google.com/issues/110573930

**Comment by Sander0542** [comment]
I don't work with maven. I downloaded the AAR of play-services-map-15.0.1 from the Google Maven repo

https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-maps/15.0.1/play-services-maps-15.0.1.aar

http://maven.google.sanderjochems.com/google-maven?group=com.google.android.gms&lib=play-services-maps&version=15.0.1

**Comment by chlegou** [comment]
@Sander0542 ah forget to mention, for imports, don't import the androidX fragment, just use the normal fragment element.
`<fragment  
        android:id="@+id/map"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        class="com.google.android.gms.maps.SupportMapFragment" />`

you can see it here, [in this samples in guithub](https://github.com/googlemaps/android-samples)


here is a class with it's layout:
class: https://github.com/googlemaps/android-samples/blob/master/ApiDemos/java/app/src/main/java/com/example/mapdemo/CameraDemoActivity.java
layout: https://github.com/googlemaps/android-samples/blob/master/ApiDemos/java/app/src/main/res/layout/camera_demo.xml

also, [follow this documentation](https://developers.google.com/maps/documentation/android-sdk/map-with-marker), and you will get it.

you can download the github project, and refractor it to androidx, and after that, update the Gmap library, and the app will work, from there, you could use any code samples you want.

this is what i did basically, to solve it. ;)

**Comment by yahiaprt** [comment]
![x](https://user-images.githubusercontent.com/51409932/60401899-df682c00-9b3c-11e9-91cb-6e5b9da5bcda.PNG)

this can solve ur issue

**Comment by memarko** [comment]
> 
> 
> ![x](https://user-images.githubusercontent.com/51409932/60401899-df682c00-9b3c-11e9-91cb-6e5b9da5bcda.PNG)
> 
> this can solve ur issue

This solved my issue. Thanks.
