### ISSUE TITLE
Changing device locale doesn't update map

### ISSUE THREAD

**Issue by ControlAdad** [googlemaps/android-samples#110]
If I open app, close app, goto device settings and change locale to another language, then come back to app, it still displays in previous language, now if I force stop app and open it again, now it's in new language.

How can I ask/force Google Map to reload locale related data? Like place labels.

Thanks

**Comment by PramodGarg** [comment]
Facing same problem? Any update on this?

**Comment by amuramoto** [comment]
Please ask how-to questions on our StackOverflow tag:

https://stackoverflow.com/questions/tagged/google-maps
