### ISSUE TITLE
How do you smooth MyLocation updates while receiving location requests through "setMyLocationEnabled" ?

### ISSUE THREAD

**Issue by Arrenign** [googlemaps/android-samples#1118]
I am currently using the "setMyLcationEnabled" to receive location on map, Even though the Blue dot and arrow appears its not smooth and lags while phone orientation changes.

Example :-  When you rotate or move the phone, The update takes a few seconds to show on the map. It's not smooth like the one in the official Google Maps app.

Any workaround or ways to fix this?

Thanks

**Comment by kikoso** [comment]
Hi @Arrenign. We would need some more information here. Performance can be based on hardware capabilities and other factors.

Could you show a relevant code snippet here, and eventually a video where we can say the lack of smoothness? 

Thanks.

**Comment by Arrenign** [comment]
Hi kikoso, It's just as simple as setting "googlemap.setMylocation(enabled)". I guess its the default behavior of the API or how it updates real time location info. Anyway I've found a workaround. 

Created a custom marker and had to receive live bearing updates from a custom attached orientation sensor. Gave me the exact smoothness of how it was in the Google maps app. Even I thought it could've been an implementation mistake or some hardware acceleration issue but then I saw multiple people raise the same issue in google forums for the map API.

Thanks,

**Comment by kikoso** [comment]
Hi @Arrenign .

Thanks for letting us know. Do you have a link for the Google Forum where this is discussed? I just can find a few entries on StackOverflow.

**Comment by Arrenign** [comment]
Hi @kikoso.

Yeah sure I actually came across multiple forums where they discussed this issue, I couldn't find the others.

One of those forums which I bookmarked is :- [https://issuetracker.google.com/issues/221374380](This)

Yeah stackover flow had a bunch too.
