### ISSUE TITLE
Could not find JAR file.

### ISSUE THREAD

**Issue by lilhumza** [googlemaps/android-samples#112]
CurrentPlaces Demo:

Gradle sync failed: Could not find aapt2-proto.jar (com.android.tools.build:aapt2-proto:0.3.1).
				Searched in the following locations:
				https://jcenter.bintray.com/com/android/tools/build/aapt2-proto/0.3.1/aapt2-proto-0.3.1.jar

**Comment by amuramoto** [comment]
The demos now all build as expected
