### ISSUE TITLE
MapWithMarker tutorial project fails with DexIndexOverflowException

### ISSUE THREAD

**Issue by Luthien-in-edhil** [googlemaps/android-samples#115]
I tried to follow the [Android map-with-marker](https://developers.google.com/maps/documentation/android-sdk/map-with-marker) tutorial - I'm completely new to Android development. I followed all the instructions, using Android Studio 3.2.1, running java version "1.8.0_144" (Mac OS 10.14.2).
When trying to build the project, it fails with the message **Cause: method ID not in [0, 0xffff]: 65536** 
This is the error stacktrace (abbreviated for readability)

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithDexForDebug'
...
Caused by: java.lang.RuntimeException: com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
...
...
Caused by: com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
	at com.android.dx.merge.DexMerger$6.updateIndex(DexMerger.java:488)
	at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:264)
	at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:497)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:191)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:522)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:344)
	at com.android.dx.command.dexer.Main.run(Main.java:292)
	at com.android.builder.internal.compiler.DexWrapper.run(DexWrapper.java:54)
	at com.android.builder.core.DexByteCodeConverter.lambda$dexInProcess$0(DexByteCodeConverter.java:173)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```

What puzzles me here is that the DexIndexOverflowException seems to be related to an app going over the "64k methods" limit - how that is possible for such a completely bare-bones Hello-World app? 

Incidentally, I noticed on importing this sample project that Android Studio prompted me to upgrade the Gradle plugin to v. 4.6. :

> (Android Gradle Plugin Update Recommended) To take advantage of the latest features, improvements, and security fixes, we strongly recommend that you update the Android Gradle plugin to version 3.2.1 and Gradle to version 4.6. Release notes  Android plugin 3.2.0 and higher now support building the Android App Bundle—a new upload format that defers APK generation and signing to compatible app stores, such as Google Play. With app bundles, you no longer have to build, sign, and manage multiple APKs, and users get smaller, more optimized downloads.

- which didn't resolve the issue.

Any idea how I can make this sample package work?

(I'm now trying to see if I can build and run the [Select Current Place and Show Details on a Map](https://developers.google.com/maps/documentation/android-sdk/current-place-tutorial) tutorial instead)

**Comment by CoolMind** [comment]
@Luthien-in-edhil, I am not new, but hasn't used this library for ages. Today has downloaded it. What I did to start.

In `gradle-wrapper.properties` updated `gradle` to 4.6:

    distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip

I received another error during build: 

> Failed to find target with hash string 'android-24' in: D:\Android
> Install missing platform(s) and sync project`.
 
I could download this outdated library, but better was update. So in `app/build.gradle` I changed all 24 to 28, `buildToolsVersion "28.0.3"`, `compile 'com.android.support:appcompat-v7:28.0.0'`.

After sync I got another error:

> The versions of the Android Gradle plugin and Gradle are not compatible.
> Please do one of the following:<ul><li>Update your plugin to version 2.4. This will require changes to build.gradle due to API changes.
> Open migration guide</li><li>Downgrade Gradle to version 3.5.
> Fix Gradle wrapper and re-import project</li></ul>

In projects's `build.gradle` I changed `classpath 'com.android.tools.build:gradle:2.2.2'` to `classpath 'com.android.tools.build:gradle:3.2.1'` and added repositories:

```
buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
I received these warnings:

> Configuration 'androidTestCompile' is obsolete and has been replaced with 'androidTestImplementation' and 'androidTestApi'.
> It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
> 
> ... (same lines)

After running (compiling) the application I got:

> AGPBI: {"kind":"error","text":"Program type already present: android.support.v4.app.FragmentTransitionCompat21$1","sources":[{}],"tool":"D8"}
> :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: C:\Users\1\AndroidStudioProjects\android-samples-master\tutorials\MapWithMarker\app\build\intermediates\transforms\dexBuilder\debug\1.jar, 

and so on

>   Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
>   Program type already present: android.support.v4.app.FragmentTransitionCompat21$1
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org

There were many other errors, I show a `app/build.gradle` file:

apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    buildToolsVersion "28.0.3"
    defaultConfig {
        applicationId "com.example.mapwithmarker"
        minSdkVersion 15
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        resValue "string", "google_maps_key", (project.findProperty("GOOGLE_MAPS_API_KEY") ?: "")
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.google.android.gms:play-services-maps:16.0.0'
    testCompile 'junit:junit:4.12'
}

configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '28.0.0'
            }
        }
    }
}

The application started with white background. I think, it is because of API KEY.

**Comment by amuramoto** [comment]
Closing since this demo appears to build fine now
