### ISSUE TITLE
 App crashing

### ISSUE THREAD

**Issue by agarwalkaushal** [googlemaps/android-samples#120]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View com.google.android.gms.maps.SupportMapFragment.getView()' on a null object reference
        at (OnMapAndViewReadyListener.java:35)

**Comment by amuramoto** [comment]
Please post debugging questions to our stackoverflow tag, and include your code:

https://stackoverflow.com/questions/tagged/google-maps
