### ISSUE TITLE
show the beam from blue dot

### ISSUE THREAD

**Issue by wanderwuuu** [googlemaps/android-samples#123]
I want show the beam from blue dot, how to set?
![SZTRd](https://user-images.githubusercontent.com/18542962/61166540-a9c23a80-a561-11e9-8a2e-ea8bf82ba18f.png)

**Comment by amuramoto** [comment]
This is not currently support, but please feel free to open a feature request for it in the issue tracker:

https://issuetracker.google.com/savedsearches/5446940
