### ISSUE TITLE
ZERO opacity for 3d buildings using custom style. 

### ISSUE THREAD

**Issue by shakesgar** [googlemaps/android-samples#125]
Hi,

3d buildings in the Maps SDK are not showing any opacity when setting the map style to a custom style.json. There are no settings in the JSON file to change this setting or when creating the map style from the style generator. 

We are using a custom style to syle the map as per our apps color palette.

Is there a modification we can do in the style_json to fix this?

![Screenshot_20190828-142626](https://user-images.githubusercontent.com/8971455/63861068-170b1d00-c9a2-11e9-9809-e77da80668ee.png)

![Screenshot_20190828-141030](https://user-images.githubusercontent.com/8971455/63861092-20948500-c9a2-11e9-9cac-40ebf5fae54f.png)

**Comment by shakesgar** [comment]
Attached two screenshots:
 - App with default map style.
 - App with our custom style.

**Comment by shakesgar** [comment]
Removing the Geometry element type will use the default color but this is useless if switching to a night mode.

**Comment by amuramoto** [comment]
afaik this is not currently supported unfortunately
