### ISSUE TITLE
Runtime permissions

### ISSUE THREAD

**Issue by ildar2** [googlemaps/android-samples#13]
I (and I presume many others) would like to see a proper guidelines on how to manage runtime permissions for Google Maps with backwards compatibility.

**Comment by bellarm** [comment]
Hi,
You can have a look at [PermissionUtils.java](https://github.com/googlemaps/android-samples/blob/master/ApiDemos/app/src/main/java/com/example/mapdemo/PermissionUtils.java) and [MyLocationDemoActivity.java](https://github.com/googlemaps/android-samples/blob/master/ApiDemos/app/src/main/java/com/example/mapdemo/MyLocationDemoActivity.java) to see an example on runtime permissions.
