### ISSUE TITLE
Maps v3-beta crash on android 5

### ISSUE THREAD

**Issue by xuaninbox** [googlemaps/android-samples#134]
When using the v3-beta on android 5, it will crash with error:

> Fatal Exception: java.lang.NoSuchFieldError
> No static field MAP_COPYRIGHTS_FULL of type I in class Lcom/google/android/libraries/maps/R$string; or its superclasses (declaration of 'com.google.android.libraries.maps.R$string' appears in /data/app/xxx/base.apk:classes2.dex)

The same error is also reported on stackoverflow, seems to be missing strings.xml
https://stackoverflow.com/questions/56690841/no-static-field-map-copyrights-full-of-type-i-in-class-lcom-google-android-libra

**Comment by jpoehnelt** [comment]
You can file an issue for this at: https://developers.google.com/maps/documentation/android-sdk/support.
