### ISSUE TITLE
Crash-> lang.NoSuchFieldError No static field MAP_COPYRIGHTS_FULL (string.xml missing for tablets )

### ISSUE THREAD

**Issue by psind** [googlemaps/android-samples#135]
The crash is happening for tablets only I have seen these crash logs for Samsung Galaxy Tab A. According to my research string .xml file is missing for tablets.

#### Stack trace
Fatal Exception: java.lang.NoSuchFieldError: No static field MAP_COPYRIGHTS_FULL of type I in class Lcom/google/android/libraries/maps/R$string; or its superclasses (declaration of 'com.google.android.libraries.maps.R$string' appears in base.apk!classes2.dex)
       at com.google.android.libraries.maps.av.zzh.<clinit>(R.java:1)
       at com.google.android.libraries.maps.bl.zzct.zzd(OverlayManager.java:155)
       at com.google.android.libraries.maps.dc.zzp.zzc(GmmRenderTarget.java:87)
       at com.google.android.apps.gmm.renderer.zzba.run(GLViewThreadImpl.java:144)

Thanks!

**Comment by ValeriiVolkov** [comment]
The same issue on handset devices with android 7.0 Nougat

**Comment by psind** [comment]
I found  a solution for this, just add these lines to your strings.xml file and you are good to go.


    
    <string name="MAP_COPYRIGHTS_GOOGLE_ONLY">© %1$d Google</string>
    <string name="MAP_COPYRIGHTS_FULL">© %1$d Google – Pictures © %2$d %3$s, Map Data © %4$d %5$s</string>
    <string name="MAP_COPYRIGHTS_IMAGERY_ONLY">© %1$d Google – Pictures © %2$d %3$s</string>
    <string name="MAP_COPYRIGHTS_MAP_DATA_ONLY">© %1$d Google – Map Data © %2$d %3$s</string>

**Comment by arriolac** [comment]
This bug was also reported here along with the workaround @psind mentioned https://b.corp.google.com/issues/132275121
