### ISSUE TITLE
Places: Please update code to new Places SDK

### ISSUE THREAD

**Issue by kishorecs** [googlemaps/android-samples#137]
Currently Maps tutorial code are using old version of SDK. 

e.g. In Project [CurrentPlaceDetailsOnMap](https://github.com/googlemaps/android-samples/tree/master/tutorials/CurrentPlaceDetailsOnMap), [gradle](https://github.com/googlemaps/android-samples/blob/master/tutorials/CurrentPlaceDetailsOnMap/app/build.gradle) file uses `play-services:11.2.0`
So when I took code and updated to `play-services:17.0.0`, I am not able to build the app.

Please someone can guide me, how to upgrade to latest SDK version.

**Comment by wangela** [comment]
Sorry about that! While I fix the sample, you can use our [migration guide](https://developers.google.com/places/android-sdk/client-migration#install_the_client_library) to add the new Places for Android SDK to your app-level build.gradle file.

**Comment by wangela** [comment]
Fixed with PR #141
