### ISSUE TITLE
MAP API KEY for com.example.mapdemo

### ISSUE THREAD

**Issue by kishorecs** [googlemaps/android-samples#138]
Hi,

I would like to know how to get debug MAP API KEY for [ApiDemos](https://github.com/googlemaps/android-samples/tree/master/ApiDemos/java)  ?
Is there any common Api Key available ?

**Comment by wangela** [comment]
There are no debug/common API keys provided. Please visit [Get Started with Google Maps Platform](https://developers.google.com/maps/gmp-get-started) to get an API key of your own. You can learn how our free trial and ongoing free tier works on our [Billing Account Credits page](https://developers.google.com/maps/billing-credits).
