### ISSUE TITLE
[Q] LiteListDemoActivity handle item click with own listener

### ISSUE THREAD

**Issue by rinav** [googlemaps/android-samples#14]
How do I disable opening full Google Maps when an item is clicked in [LiteListDemoActivity.java](https://github.com/googlemaps/android-samples/blob/master/ApiDemos/app/src/main/java/com/example/mapdemo/LiteListDemoActivity.java)?
I do not see any click listeners implemented in the example, **I wonder from where click is getting triggering, and default Google Maps app gets opened**

I want to have my own click listener which open Map with some GeoFencing stuff

**Comment by bellarm** [comment]
Hi,
You can make your class implements `OnMapClickListener`, and set the on map click listener of each GoogleMap objects. Please have a look at the [support page](https://developers.google.com/maps/documentation/android-api/support) if you still have questions.
