### ISSUE TITLE
How do I get 3D view in map on clicking mylocation button?

### ISSUE THREAD

**Issue by omkarkhalipe** [googlemaps/android-samples#148]
Hi! I am trying to get a 3d map view on clicking my location button on whatsapp or google maps app, like the one in screenshot below. that icon shows up on clicking my location button, but in my app it doesn't show up.
![Screenshot_2020-03-26-02-16-31-84](https://user-images.githubusercontent.com/15224429/77594674-22fd9400-6f1d-11ea-9ce6-94bf7ddb4a54.jpg)

**Comment by arriolac** [comment]
Hi @omkarkhalipe, thanks for stopping by. 

Unfortunately there are no public APIs to support 3D following at the moment. If you would like to implement behavior like that, you will need to implement yourself using a combination of `SensorManager` and `GoogleMap` settings (enable tilt). It would be cool to create a sample for how to implement that in this repo though.

Closing this issue. Let me know if you have other questions.
