### ISSUE TITLE
Maps 3 beta and FusedLocationProviderClient

### ISSUE THREAD

**Issue by MithrilMan** [googlemaps/android-samples#149]
I've a code working with map sdk 2 and I'm trying to port it to v3 beta
I'm making use of FusedLocationProviderClient, LocationRequest/LocationCallback but I can't find these classes in the new package, are they not implemented yet?

**Comment by arriolac** [comment]
Only maps-related classes were affected. So pretty much `com.google.android.gms.maps` and `com.google.android.gms.maps.model` were moved to `com.google.android.libraries.maps` and `com.google.android.libraries.maps.model`, respectively. 

For location-related services like `FusedLocationProviderClient` etc., you will still need to integrate with Google Play Services.

**Comment by MithrilMan** [comment]
ok so there isn't any plan about removing Google Play Services as a whole for maps usage?
thanks for clarification.

**Comment by arriolac** [comment]
> ok so there isn't any plan about removing Google Play Services as a whole for maps usage?
> thanks for clarification.

These are still under consideration. As of now, the standalone maps is still in beta and the maps in Google Play Services is still the official distribution. In your case, if you are using Maps 3 beta and require other location services in Google Play Services, you'll have to include those additional dependencies.
