### ISSUE TITLE
Incorrect call to super for onDestroy 

### ISSUE THREAD

**Issue by squeeish** [googlemaps/android-samples#17]
At https://github.com/googlemaps/android-samples/blob/master/ApiDemos/app/src/main/java/com/example/mapdemo/StreetViewPanoramaViewDemoActivity.java :

```
@Override
protected void onDestroy() {
    mStreetViewPanoramaView.onDestroy();
    super.onPause();
}
```

Is it supposed to be `super.onDestroy()`?

**Comment by stephenmcd** [comment]
Well spotted, thank you.
