### ISSUE TITLE
google-play-services-maps:17.0.0 is not working even with default project Android Studio created

### ISSUE THREAD

**Issue by sadeq9128** [googlemaps/android-samples#182]
Hi. please help me...
I want to create a project based on Google Maps. But after building gradle in Android Studio, The following error occurs:

ERROR: Failed to resolve: com.google.android.gms:play-services-maps:17.0.0
Install Repository and sync project
Show in Project Structure dialog
Affected Modules: app

When i clicked on the 'Install Repository and ...' then this message appear:

Could not find dependency "com.google.android.gms:play-services-maps:17.0.0"

NOTE:
i went to Setting and Android SDK then downloaded google play services.. but it is not working for me.

**Comment by Ayush-21** [comment]
Same error

**Comment by Ayush-21** [comment]
Still valid

**Comment by arriolac** [comment]
Did you make sure that `google()` is added as a repository? In your top-level `build.gradle` file:
```
allprojects {
    repositories {
        google()
    }
}
```

**Comment by Klexis** [comment]
Still a problem

**Comment by Klexis** [comment]
> Hi. please help me...
> I want to create a project based on Google Maps. But after building gradle in Android Studio, The following error occurs:
> 
> ERROR: Failed to resolve: com.google.android.gms:play-services-maps:17.0.0
> Install Repository and sync project
> Show in Project Structure dialog
> Affected Modules: app
> 
> When i clicked on the 'Install Repository and ...' then this message appear:
> 
> Could not find dependency "com.google.android.gms:play-services-maps:17.0.0"
> 
> NOTE:
> i went to Setting and Android SDK then downloaded google play services.. but it is not working for me.

Did it work??????
