### ISSUE TITLE
how to detect which polygon clicked?

### ISSUE THREAD

**Issue by d7coders** [googlemaps/android-samples#19]
@Override
    public void onPolygonClick(Polygon polygon) {

```
}
```

**Comment by morrisontech** [comment]
I think you can do a HashMap or some other data structure and reference it by Polygon.getID() within the OnPolygonClickListener implementation. I did something similar with Polylines.

**Comment by andrewindayang** [comment]
When you draw your polygon, you can use Hash map to store the object with the polygon ID.

e.g :     private Map<String, Object> markerMap;
            markerMap.put(polygon.getId(), OBJECT);

to retrieve : 
                    Object data = (Object) markerMap.get(polygon.getId()); --> you can get everything from the object.

**Comment by bellarm** [comment]
Hi,
It looks like you have solved your problem. Have a look at the [support page](https://developers.google.com/maps/documentation/android-api/support) if you still have any questions.
