### ISSUE TITLE
markers cannot show Hebrew text

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googlemaps/android-samples#2]
Maybe also Arabic.
Here's what I get for putting a title in Hebrew of the word "Israel" ("ישראל")  :

![device-2015-12-03-111306](https://cloud.githubusercontent.com/assets/5357526/11556376/dda6fad8-99ae-11e5-86af-850c71ed6ab8.png)

Here's the code:

```
                        mMap.addMarker(new MarkerOptions()
                                .position(latLng)
                                .title(locationTitle)
                                .snippet("snippet")
                                .icon(BitmapDescriptorFactory.fromResource(R.drawable.arrow))
                                .infoWindowAnchor(0.5f, 0.5f));
```

BTW, the map is wrong for Israel's borders. It has the north-east area ("Ramat Hagolan") for a very long time. It doesn't make sense to show the old borders of before the wars.

Israel also includes the west bank and the east area ("Yehuda" and "Shomron"), which is also why it's ok to travel to the entire Jordan river.
It's just that those areas are problematic (except for Ramat Hagolan, which isn't problematic at all)

**Comment by AndroidDeveloperLB** [comment]
The bug occurs even when using a customized InfoWindowAdapter, which I don't understand how could it be.

**Comment by bellarm** [comment]
Hi,
This issue has been reported [here](https://issuetracker.google.com/issues/35823358), so I'm going to close the issue.

**Comment by AndroidDeveloperLB** [comment]
@bellarm OK. Please also fix the borders issue. Here's more information about the north-east part ("Golan Heights" , and in Hebrew it's called "Ramat Hagolan" - "רמת הגולן" ) :
https://en.wikipedia.org/wiki/Golan_Heights
It's a part of Israel, and is completely safe to travel there.
