### ISSUE TITLE
How to show the location and map in ViewPager or TabBar Layout fragment is it possible to do?

### ISSUE THREAD

**Issue by mohanrajsambath** [googlemaps/android-samples#20]
Sorry supposed to my issue is not related to the this code,please concern my request,I presently show the map is in one of the tab, so here i follow the support fragment to show the Map, Map shows perfectly, but i don't know how to show the location marker in map. please help me, its my kind request.

**Comment by paulpv** [comment]
https://github.com/googlemaps/android-samples/blob/master/ApiDemos/app/src/main/java/com/example/mapdemo/MyLocationDemoActivity.java

**Comment by achillies47** [comment]
what about the "  PermissionUtils  " ?

what should i initialize in the that class ?

**Comment by paulpv** [comment]
https://github.com/googlemaps/android-samples/blob/master/ApiDemos/app/src/main/java/com/example/mapdemo/PermissionUtils.java

**Comment by bellarm** [comment]
Hi,
If you want to add a Marker in ViewPager (like in the [MapInPagerDemoActivity](https://github.com/googlemaps/android-samples/blob/master/ApiDemos/app/src/main/java/com/example/mapdemo/MapInPagerDemoActivity.java)) you can do this inside `getItem()`
```
SupportMapFragment supportMapFragment = SupportMapFragment.newInstance();
supportMapFragment.getMapAsync(new OnMapReadyCallback() {
    @Override
    public void onMapReady(GoogleMap googleMap) {
        googleMap.addMarker(new MarkerOptions()
                .position(new LatLng(0, 0))
                .title("Marker"));
    }
});
return supportMapFragment;
```
If you still need any help with the Google Maps Android API please have a look at the [support page](https://developers.google.com/maps/documentation/android-api/support).
