### ISSUE TITLE
centre of polygon has hole --> island

### ISSUE THREAD

**Issue by andrewindayang** [googlemaps/android-samples#22]
I couldn't fix this problem where I draw polygon and the centre of my polygon has island and the polygon just fill the colour of the small island. instead of I want that to be fill the whole things. I have tried multiple solutions : counter-clockwise , colour problem. is that possible if you answer for this. I have attached image on this post. thank you
<img width="371" alt="screen shot 2016-07-14 at 9 58 18 am" src="https://cloud.githubusercontent.com/assets/5306027/16823734/854bde2a-49a9-11e6-882d-37e15a228783.png">

**Comment by katherineallen** [comment]
To add a hole in a filled polygon, use the addHole() method. This method is documented [here](https://developers.google.com/maps/documentation/android-api/shapes#polygons) and is used in the PolygonDemoActivity in the API Demos app in this repository.
