### ISSUE TITLE
Marker is not Showing on the Map

### ISSUE THREAD

**Issue by UmarBhutta** [googlemaps/android-samples#23]
getting warning in the logs : Google Maps Android API: GLHudOverlay deprecated; draw(): no-op

Please update it i am using com.google.android.gms:play-services-maps:9.4.0

**Comment by katherineallen** [comment]
Hi,

This issue was fixed in the September 21 2016 release of the API, notes for which are [here](https://developers.google.com/maps/documentation/android-api/releases#september_21_2016).
