### ISSUE TITLE
Update Readme to fit secure.properties

### ISSUE THREAD

**Issue by xLuckyOne** [googlemaps/android-samples#247]
Hey, 

in the Readme.md the setup for the API key is still described as:
_Search for YOUR_API_KEY in the project and replace it with your API key. Some samples store this in the gradle.properties file and others store it in the google_maps_api.xml file. See the Get Started with Google Maps Platform guide to get an API key._
Browsing the Files, I found out that you implemented the API-key in a secure.properties file, could you update the Readme so future users find it faster?

Cheers!

**Comment by arriolac** [comment]
Thanks for reporting. The samples require that you create a `secure.properties` file per sample, however, it would be much more convenient to create a single `secure.properties` file at the root of the repository and have all samples reference that. I'll work on updating this along with the documentation.
