### ISSUE TITLE
My Location Demo isn't able to zoom to one's location

### ISSUE THREAD

**Issue by cjkrieseSF** [googlemaps/android-samples#25]
Although the marker is present at the correct location, the map remains zoomed out and center at geographic midpoints for latitude and longitude... in the middle of the Atlantic Ocean.  Manually scrolling and zooming does reveal the correctly placed marker.

The Android Monitor window is full of lines similar to the following:
09-05 13:12:34.456 14247-15011/com.example.mapdemo W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op

**Comment by paulpv** [comment]
You have to control the zoom level yourself.
These are just basic samples, and a production app needs to be a bit more complicated.

I think you can ignore those deprecated draw warnings.
I see a lot of these too, mostly in my Genymotion 6.x VM.
On what device model and version of Android for you?

**Comment by katherineallen** [comment]
Hi,

This sample was updated in pull request #66 to use a connectionless client, and now zooms to show the user's current location.
