### ISSUE TITLE
Memory leak in Lite mode

### ISSUE THREAD

**Issue by Tyomnuy** [googlemaps/android-samples#27]
There is a memory leak in `LiteDemoActivity`. 

After opening `LiteDemoActivity` (clicking on "Lite Mode") and going back for `n` times you will get `n` leaked instances of LiteDemoActivity.

**Comment by katherineallen** [comment]
Hi, this issue is best reported in the Google Maps Android API issue tracker, which it seems to have been [here](https://issuetracker.google.com/issues/35829622), so I'm going to close this issue here for now.
