### ISSUE TITLE
Crash on Xiaomi Mi 9T Pro (Out of Memory or GPU related)?

### ISSUE THREAD

**Issue by ArcherEmiya05** [googlemaps/android-samples#282]
Good day, I am moving a marker with these lines of code every time there is a location update.

        cameraBuilder.bearing((float) MarkerUtil.bearingBetweenLocations(from, to))
        .target(to)
        .zoom(16f);

       cameraBuilder.tilt(0).zoom(16f);

        CameraPosition position = cameraBuilder.build();
        CameraUpdate cameraUpdateFactory = CameraUpdateFactory.newCameraPosition(position);

        mMap.animateCamera(cameraUpdateFactory);

        final ValueAnimator valueAnimator = ValueAnimator.ofFloat(0, 1).setDuration(3000);
        final MarkerUtil.LatLngInterpolatorNew latLngInterpolator = new MarkerUtil.LatLngInterpolatorNew.LinearFixed();
        valueAnimator.setInterpolator(new LinearInterpolator());
        valueAnimator.addUpdateListener(valueAnimator1 -> {

            if (isDestroyed())
                return;

            float v = valueAnimator1.getAnimatedFraction();
            LatLng newPos = latLngInterpolator.interpolate(v, from, to);
            currentMark.setPosition(newPos);
            currentMark.setAnchor(0.5F, 0.5F);
            currentMark.setRotation((float) MarkerUtil.bearingBetweenLocations(from, to));
            oldLatLng = to;

        });
        valueAnimator.start();

And it works fine but when I change the camera view and angle with this
`cameraBuilder.tilt(90).zoom(20f);`

then move around for a couple of seconds it will crash but all I got from logcat was a huge number of this:
`2020-08-26 15:16:27.588 11903-16505/? E/Adreno-GSL: <gsl_memory_alloc_pure:2297>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
W/Adreno-GSL: <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory`

So far I only tested this with 2 device and only occur with Xiaomi Mi 9T Pro device but everything seems okay on LG K10 K430dsy.

**Comment by arriolac** [comment]
Looks like this issue isn't related to the samples available in this repository and instead potentially an issue with the Maps SDK for Android itself. I recommend filing this on our [Issue Tracker](https://issuetracker.google.com/issues/new?component=188833&template=789005) to receive better support. Please also provide a more detailed stack trace to help with debugging this issue.
