### ISSUE TITLE
How to update Google Play services on Emulator?

### ISSUE THREAD

**Issue by nhoang53** [googlemaps/android-samples#29]
I got the Key and set restrict, but I still cannot open map on the Emulator. On the build.gradle, I saw that the google play service is 9.8.0 now, and I think this is the newest one. However, when I run the sample-app, it say I need to update Google Play service?

`dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.google.android.gms:play-services-maps:9.8.0'
}`

I check on the Android Emulator that it doesn't have Play store. Is it the missing one? I follow this link 
https://developers.google.com/maps/documentation/android-api/start#step_2_install_the_google_play_services_sdk

to install Google Play services but I cannot found anything that can help. My Android studio version is 2.2.2.
I download the GooglePlayServices apk file (com.google.android.gms-9.8.77-440-135396225-APK4Fun.com), I dragged and dropped it into emulator to install, but it has error
`Error: INSTALL FAIL INCOMPATIABLE`

I need your help.

**Comment by bilbanmehmet** [comment]
I live the same problem. Can you help me with the question?

**Comment by nhoang53** [comment]
Oh you can run it on your physical device or you have to downgrade the version of Google service on AndroidMenifest to 9.6.0 
http://stackoverflow.com/questions/40268805/how-to-update-google-play-service-on-emulator-android-studio/40375645#40375645
(Rate it if it can help you)

Sent from Yahoo Mail on Android 
 
  On Fri, Nov 18, 2016 at 12:40 AM, bilbanmehmet<notifications@github.com> wrote:   
I live the same problem. Can you help me with the question?

**Comment by bilbanmehmet** [comment]
it worked. Thanks:)

**Comment by FernandaBorges** [comment]
Baixei a imagem do android 8 oreo e o emulador funcionou o mapa direitinho.
