### ISSUE TITLE
Toggle map markers to show or hide from CheckBox

### ISSUE THREAD

**Issue by Tecmek** [googlemaps/android-samples#377]
I've searched everywhere that I could think of, but I haven't been able to find anything about using a CheckBox to show or hide markers on .isClicked I have tried multiple ways but so far nothing is working. Any suggestions?

**Comment by arriolac** [comment]
You'll need to store a reference to all your `Marker` objects that you want to show/hide and use the [Marker#setVisible(boolean)](https://developers.google.com/android/reference/com/google/android/gms/maps/model/Marker#setVisible(boolean)) method to show/hide.

**Comment by Tecmek** [comment]
I have a mapOf that holds my location title and latlng, then I have in another function a mutableMapOf that calls each location and adds the marker to the position and the snippet for that location. Should I create a separate mutableMapOf for each category and marked.swtVisible the who list or could I just put them all in the same list and just use the .setVisible? Sorry I'm very new. Thank you for your help!

**Comment by arriolac** [comment]
Is this still an issue for you? Can you share a code snippet?

**Comment by Tecmek** [comment]
I was able to resolve the issue, it was an error on my part, I was using sharedPreferences and I was saving it to the wrong key. it is working properly now. Thank you!
