### ISSUE TITLE
Standard API: map lagging while moving and a dialog pops over it

### ISSUE THREAD

**Issue by dkati** [googlemaps/android-samples#379]
Tested on:
Android 8  (snapdragon 8xx - 8 ram)
Android 10  (snapdragon 8xx - 8 ram)
Android 5.0 on samsung device (jfltexx - S4 )

#### Tested on
  1. googlemaps/android-samples demo
  2. googlemaps/android-maps-utils demo

Using pure java (no kotlin at all)

**Fun fact: Does NOT happening on Google Maps app!**

#### Steps to reproduce

  1. create a map
  2. add a fab (or something) and on it's click listener zoom to your location
  3. run the app and zoom fully out (see the earth)
  4. press the fab 
  5. While camera animation is going, pull your QuickSettings panel OR on fab's listener also create an alert dialog
  6. see the background map is laggy

or , if you use a demo from googlemaps/android-samples demo or googlemaps/android-maps-utils you can reproduce this 
by quickly swipe-to-move-camera and pull QS panel

By my "research" it happens on any dialog (QS panel, alert dialog, fragmentdialog, progress dialog, bottom dialog)
but it doesnt happens on fragments

Generally, poping any dialog over maps, also spams: 
E/SchedPolicy: set_timerslack_ns write failed: Operation not permitted
on app's log

**Comment by dkati** [comment]
Thanks @barbeau

**Comment by arriolac** [comment]
Hi @dkati thanks for reporting. Since this is an issue with the Maps SDK itself, please file this issue here: https://issuetracker.google.com/issues/new?component=188870&template=788712 If you have an example app demonstrating this that you can share when you report it that would be great.

**Comment by dkati** [comment]
Good evening! i just shared it to issuetracker. 
About example app, as i said at OP , this can be reproduced with any demo example from both maps examples and utils

**Comment by jhonpaul0724** [comment]
@dkati may I ask how you solved the E/libprocessgroup: set_timerslack_ns write failed: Operation not permitted?

**Comment by dkati** [comment]
It's not Google maps related. Didn't solve it

**Comment by jhonpaul0724** [comment]
I think it needs us to enable the billing in the google api

**Comment by kikoso** [comment]
Closing this issue, since it is related to the Maps SDK.
