### ISSUE TITLE
error using newlatlngbounds(latlngbounds,int): Map size can't be 0. most likely, layout has not yet occured for the map view

### ISSUE THREAD

**Issue by Royhan18** [googlemaps/android-samples#399]
Im coding for android with expo. Then i found this problem

error using newlatlngbounds(latlngbounds,int): Map size can't be 0. most likely, layout has not yet occured for the map view. Either wait until layout has occurred or use newLatLngBounds(LatLngBounds, int, int, int) which allows you to specify the map's dimensions.

This is my code
[MapComponent.txt](https://github.com/googlemaps/android-samples/files/5614187/MapComponent.txt)

**Comment by arriolac** [comment]
Hi @Royhan18, the snippet you shared appears to be related to the React Native Maps SDK component and not the Java or Kotlin version. I suggest asking in that repo instead to receive better support https://github.com/react-native-maps/react-native-maps
