### ISSUE TITLE
Not able to load the maps from android-samples

### ISSUE THREAD

**Issue by Nildevelope** [googlemaps/android-samples#409]
I have downloaded android-samples and imported the project in android studio.

After importing as per the instructions I have enable the billing account and created the API key for the project by providing package name as com.example.mapdemo as it is in demo apps provided.

But when I run the project map view is not getting loaded instead blank screen with google written on the bottom left corner screen is appearing.

Attaching the logs snapshot and app screenshot for reference.

<img width="849" alt="Issue_logcat" src="https://user-images.githubusercontent.com/68062476/102972696-79861600-4521-11eb-991b-531e5aa924d0.PNG">
![device-2020-12-23-131418](https://user-images.githubusercontent.com/68062476/102972801-a2a6a680-4521-11eb-8efd-cca418bfdf74.png)

**Comment by arriolac** [comment]
Hi @Nildevelope, looks like the API key you aded has some restrictions in place that aren't configured correctly. I suggest either creating a new API key or adjusting the restrictions in place to fix that. See: https://developers.google.com/maps/documentation/android-sdk/get-api-key#restrict_key

**Comment by arriolac** [comment]
Closing this. Please reopen if you are still having issues.
