### ISSUE TITLE
Sample Request : LiteListDemoActivity (or anything similar) with recyclerView instead of ListView

### ISSUE THREAD

**Issue by morphine9** [googlemaps/android-samples#41]
More specifically I'm finding it a tad built difficult to implement a properly recycled/optimized MapView/MapFragment on a heterogeneous recycler view (e.g., **row items with 2 or more item types**)

Any pointers with be really appreciated around [RecylerListener](https://github.com/googlemaps/android-samples/blob/master/ApiDemos/app/src/main/java/com/example/mapdemo/LiteListDemoActivity.java#L198)

**Comment by bellarm** [comment]
Hi, the LiteListDemo has been updated to use RecyclerView. I'm going to close the issue now.
