### ISSUE TITLE
截屏

### ISSUE THREAD

**Issue by aixiaolinzi** [googlemaps/android-samples#42]
问题解决。。

**Comment by aixiaolinzi** [comment]
问题已经解决。
http://stackoverflow.com/questions/13773658/capture-screen-shot-of-googlemap-android-api-v2

public void captureScreen()
    {
       SnapshotReadyCallback callback = new SnapshotReadyCallback() 
        {
            @Override
            public void onSnapshotReady(Bitmap snapshot) 
            {
           
            }
        };
        mMap.snapshot(callback);
    }
这样就可以拿到地图的截图。。

**Comment by katherineallen** [comment]
Hi, 

Seems like you've solved your problem, so I'm going to close this issue for now.
