### ISSUE TITLE
Inconsistency between code sample and Google's SDK documentation

### ISSUE THREAD

**Issue by antonsurya** [googlemaps/android-samples#468]
Code sample uses `MAPS_API_KEY`:

https://github.com/googlemaps/android-samples/blob/7c4167c2319111c7668d14414b39bd57f5e53e97/ApiDemos/kotlin/app/src/v3/java/com/example/kotlindemos/MainActivity.kt#L59

But Google's documentation for the SDK uses `mapsApiKey`:

https://developers.google.com/maps/documentation/android-sdk/get-api-key#add_key

So if you follow the guide in Google's documentation, the app will show a toast message "Add your own API key in local.properties as MAPS_API_KEY=YOUR_API_KEY". Despite the toast message, the app shows a map successfully.

**Comment by arriolac** [comment]
Thanks for pointing out this inconsistency. Will fix.

**Comment by arriolac** [comment]
A fix is in place and the docs will be updated shortly.
