### ISSUE TITLE
Question: How to show entire world map ?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googlemaps/android-samples#49]
If it's not a good place to ask this, I've made a question on StackOverflow:
http://stackoverflow.com/q/42329186/878126

**Comment by AndroidDeveloperLB** [comment]
Why close this?

**Comment by amuramoto** [comment]
The stackoverflow question is the right place for this type of question

**Comment by AndroidDeveloperLB** [comment]
@amuramoto Is he correct on what he showed though?
And why only lite mode is available for it?
What about the default one?
