### ISSUE TITLE
Add RecyclerView example

### ISSUE THREAD

**Issue by jush** [googlemaps/android-samples#5]
[LiteListDemoActivity.java](https://github.com/googlemaps/android-samples/blob/master/ApiDemos%2Fapp%2Fsrc%2Fmain%2Fjava%2Fcom%2Fexample%2Fmapdemo%2FLiteListDemoActivity.java) provides a nice example for using a Google Maps lite inside a `ListFragment`.

Could you please add a similar example but using [RecyclerView](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.html)?

**Comment by bellarm** [comment]
Hi, the LiteListDemo has been updated to use RecyclerView. I'm going to close the issue now. #88
