### ISSUE TITLE
Please update your google play service

### ISSUE THREAD

**Issue by jeinstein** [googlemaps/android-samples#50]
I am trying to run this app. I have tried to follow the link on:
http://stackoverflow.com/questions/35476182/updating-google-play-services-in-emulator
and 
http://stackoverflow.com/questions/35476182/updating-google-play-services-in-emulator

It still unable to solve the issue. 

Below is my android studio settings. I am unable to figure out how my google play service can have 10.2.0 version. i have tried to reinstall the latest sdk, rebuild sync gradle, etc. I also have tried to downgrade the compile in gradle from 10.2.0 to 10.0.84 to match my android play version but it creates other issues having no reference to some of the functions used. I have spent  4hours trying to figure this out but having no results. can someone please help? Thanks.
![image](https://cloud.githubusercontent.com/assets/10785467/23165592/0efe7ea2-f891-11e6-8a47-059ad2326254.png)
![image](https://cloud.githubusercontent.com/assets/10785467/23165602/195afe02-f891-11e6-9f04-427edab1314b.png)
![image](https://cloud.githubusercontent.com/assets/10785467/23165633/3c071a12-f891-11e6-9fdd-0b5870a509a4.png)

![image](https://cloud.githubusercontent.com/assets/10785467/23165564/ec0f4426-f890-11e6-8789-44ed67afb742.png)
![image](https://cloud.githubusercontent.com/assets/10785467/23165581/04eea23e-f891-11e6-8ad9-5ef045507e14.png)

**Comment by mejimaru** [comment]
Hello bro,

Try to downgrade to 9.6.0, It's worked for me.

**Comment by tenya** [comment]
I update the latest open_gapp and fix the problem.
