### ISSUE TITLE
Google Maps Offline

### ISSUE THREAD

**Issue by blackbirdsr71br** [googlemaps/android-samples#52]
Good afternoon.

Is there any way to use offline maps, as it does in the application of google maps in my apolicacion developed with Android Studio?

**Comment by abraaocaldas** [comment]
As far as I know if you download an area on Google Maps it will automatically available for any application using google maps api.

**Comment by SlavVv** [comment]
Is this still applicable, can someone confirm it, because it will reduce drastically the usage of internet and without the need of update of selected area for (let's say) one week, there will be no need for extra requests which will also result in less power drained from the battery.

**Comment by whyzjl** [comment]
how to download an area？

**Comment by gao746700783** [comment]
afternoon.
how can i use offline map data using google map api?

**Comment by domesticmouse** [comment]
Please see [this page](https://developers.google.com/maps/support/) for support options for Google Maps APIs. Thanks!
