### ISSUE TITLE
Maps Lite mode with incorrect zoom level first time app starts. 

### ISSUE THREAD

**Issue by pranayairan** [googlemaps/android-samples#54]
If you open map view lite mode, either liteDemoActivity or liteListDemo very first time the app is run, the maps comes with incorrect Zoom levels. 

If you exit this screen and come back, you will see the maps with correct zoom level. Same issue on both lite Demo and liteList. In lite demo activity, click on Adelaide to see the difference.

Steps to reproduce : 

- Open the app, go to liteListDemo, observe the zoom level, now exit the screen by pressing back button. 

- Open the liteListDemo again and you should see maps with correct zoom level. 

- Kill the app from recent task, and open again to reproduce the issue.

**Comment by jush** [comment]
It seems there's a bug report for it already.
Please star the bug at https://issuetracker.google.com/issues/36218443

**Comment by katherineallen** [comment]
As this is now recorded on the API's Issue Tracker at the link above, I'm going to close this here for now.
