### ISSUE TITLE
OnClick listener on custom info window of marker

### ISSUE THREAD

**Issue by HasanShaikh** [googlemaps/android-samples#56]
Is it possible to set the onclick listener on custom info window contents, like textview and imageview.
Please help me out if you can do this in marker demo activity.

**Comment by katherineallen** [comment]
Hi Hasan,

Based on the documentation [here](https://developers.google.com/maps/documentation/android-api/infowindows) (specifically the note about custom info windows, as well as the final paragraph) it is not possible to set listeners for the different components of a custom info window, as the info window is rendered as an image.

You can, however, set a listener for the entire info window, as demonstrated with onInfoWindowClick and onInfoWindowLongClick in MarkerDemoActivity.java
