### ISSUE TITLE
Error: File path too long on Windows, keep below 240 characters

### ISSUE THREAD

**Issue by thomaskanzig** [googlemaps/android-samples#57]
After I download and building apk appear this error below:

Error:Error: File path too long on Windows, keep below 240 characters : C:\ThomasKanzigProjects\App\Android\Apps (examples)\android-samples-master\ApiDemos\app\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.0\res\drawable-xxhdpi-v4\common_google_signin_btn_icon_light_normal_background.9.png

What suppest I have to do?

**Comment by russellblog** [comment]
for long path issues, i recommend you long path tool software.
