### ISSUE TITLE
Current Location

### ISSUE THREAD

**Issue by gelaiye** [googlemaps/android-samples#63]
I'am chiness , I hava a problem , when I use this demo,  "mLastKnownLocation" always equals null , so I can't get  Latitude and Longitude, In my project , I only need   Latitude and Longitude  ,so I am not use Google Map , then cause this problem.   ( mLastKnownLocation = LocationServices.FusedLocationApi
                    .getLastLocation(mGoogleApiClient); )  ,  I want you help me solve  this problem , thank you!

**Comment by wangela** [comment]
Fixed with null check in PR #141
