### ISSUE TITLE
Location package doesn't exist

### ISSUE THREAD

**Issue by OLGANJA** [googlemaps/android-samples#64]
Try to make Sample App as in tutorial - 
https://developers.google.com/maps/documentation/android-api/current-places-tutorial?hl=ru

But when do so get an error message - 
Error:(31, 39) error: package com.google.android.gms.location does not exist

At the top there is import of
import com.google.android.gms.location.LocationServices;
like in the sample.
Why this error displays and how to fix it?

**Comment by Akronix** [comment]
Do you have play-services-location in your build.gradle file?
You should have a line similar to this in app/build.gradle:
`compile 'com.google.android.gms:play-services-location:11.0.4'`
