### ISSUE TITLE
How do I display the Street View area in android sdk？

### ISSUE THREAD

**Issue by peng093** [googlemaps/android-samples#670]
![strView](https://user-images.githubusercontent.com/30769746/129671737-9d706097-5f91-4da1-bf38-7763cfe49e12.png)
Similar to the Web version of the street View display

**Comment by arriolac** [comment]
See the [Street View](https://developers.google.com/maps/documentation/android-sdk/streetview?hl=en) documentation which contains guides and sample code/snippets to help you use this API.

**Comment by peng093** [comment]
> See the [Street View](https://developers.google.com/maps/documentation/android-sdk/streetview?hl=en) documentation which contains guides and sample code/snippets to help you use this API.

The documentation does not have a way to implement a street view area
