### ISSUE TITLE
CurrentPlaceDetailsOnMap: task.isSuccessful issue on placeResult.addOnCompleteListener 

### ISSUE THREAD

**Issue by paragones** [googlemaps/android-samples#73]
I have just cloned the whole android-samples library and tried to run the `CurrentPlaceDetailsOnMap` project. I have done all the instructions given to me including creating my own API. However, everytime I just clicked `Get Place`, I get this error:

```E/MapsActivityCurrentPlace: Exception: %s
 com.google.android.gms.common.api.ApiException: 13: ERROR
 at com.google.android.gms.common.internal.zzb.zzx(Unknown Source)
 at com.google.android.gms.common.internal.zzbj.zzy(Unknown Source)
 at com.google.android.gms.common.internal.zzbk.zzp(Unknown Source)
 at com.google.android.gms.common.api.internal.zzs.zzc(Unknown Source)
 at com.google.android.gms.common.api.internal.zzs.setResult(Unknown Source)
 at com.google.android.gms.location.places.zzm.zzao(Unknown Source)
 at com.google.android.gms.location.places.internal.zzx.onTransact(Unknown Source)
 at android.os.Binder.execTransact(Binder.java:573)
```

I didn't change anything.

**Comment by feinstein** [comment]
Same problem here...

**Comment by nabeelpkl** [comment]
@paragones Did you find any solution for this?

**Comment by feinstein** [comment]
I did, I just forgot to say it here, I am sorry.

You need to include the Places API on your Google Cloud Console, the same way you added the Maps API. 

The error is very cryptic and Google should have documented it better, and but it means your app doesn't have permissions to access the Places API.

**Comment by nabeelpkl** [comment]
@feinstein thanks for the reply. still couldn't find the solution. can you explain the steps you have gone through?

**Comment by feinstein** [comment]
I won't remember every singe detail, but search for how to enable some Google API, on the Google APIConsole, and you will see a huge list of Google APIs there, I think it's on the Library section of the Google Cloud Console.

**Comment by nabeelpkl** [comment]
Enabled Google Places API for Android from Developer Console Library section of the project. Still getting same error. 
<img width="1022" alt="screen shot 2017-11-12 at 12 20 25 pm" src="https://user-images.githubusercontent.com/2047178/32696658-ed3315a2-c7a3-11e7-997a-7738ba2921e2.png">

**Comment by feinstein** [comment]
I am sorry, but this worked for me. Maybe you have some other APIs that need authorization? Maybe your maps API key isn't set properly... I don't know.. Sorry if I can't help much more than that.

**Comment by nabeelpkl** [comment]
Cant find a workaround. @feinstein thanks for your time.

**Comment by sheldonhall** [comment]
Hi, I seem to have this exact issue. Whether or not I use the API as restricted, I get the same exception. 

Project gradle dependencies:


    dependencies {
         classpath 'com.android.tools.build:gradle:3.0.0'
        classpath 'com.google.gms:google-services:3.1.1'
    }


Module gradle dependencies:


    dependencies {

        implementation fileTree(dir: 'libs', include: ['*.jar'])
        testImplementation 'junit:junit:4.12'
        implementation 'com.android.support:appcompat-v7:26.0.2'
        implementation 'com.android.support:support-v4:26.0.2'
        implementation 'com.android.support:cardview-v7:26.0.2'
        implementation 'com.squareup.okhttp3:okhttp:3.0.1'
        implementation 'com.android.support:design:26.0.2'
        implementation 'org.atteo:evo-inflector:1.2.1'
        implementation 'com.google.android.gms:play-services-location:11.6.0'
        implementation 'com.google.android.gms:play-services-places:11.6.0'
        implementation 'com.squareup.picasso:picasso:2.5.2'
        annotationProcessor 'com.bluelinelabs:logansquare-compiler:1.3.6'
        implementation 'com.bluelinelabs:logansquare:1.3.6'
        implementation 'com.jakewharton:butterknife:8.8.1'
        annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
    }

**Comment by nabeelpkl** [comment]
Worked for me after adding 
```
<meta-data
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />
```
in `AndroidManifest.xml`

Please see this [thread](https://stackoverflow.com/a/47448899/1769274).

**Comment by sheldonhall** [comment]
No that doesn't seem to solve the problem nor any of the solutions in that thread. Two thoughts are occurring to me this point:

1. That's just a generic exception for "Your setup to this API is incorrect" and it could exist for a number of different reasons.

2. Perhaps it's something fundamental that I'm missing that isn't enabling the api in the console.

Can you share the source you used for this example? android-samples library?

**Comment by rt9092** [comment]
@sheldonhall  Please check if you have location services enabled on your device? I had the same problem and it kept throwing the exception because location services were disabled on my device. Try turning on the location services

**Comment by sheldonhall** [comment]
It's on as far as I can tell. Google maps work on the emulator

<img width="381" alt="screen shot 2017-11-23 at 8 40 28 am" src="https://user-images.githubusercontent.com/5139845/33173319-174fb4ba-d02a-11e7-9bdd-dce5869cafe5.png">

**Comment by rt9092** [comment]
Are you supplying current location to Emulator using DDMS? You will have to give emulator a LatLng to work with. It does not have a location by default. Google Maps will work until and unless you do some work on it by using some LatLng.

**Comment by sheldonhall** [comment]
Yeah I am, in fact the location of the emulated device isn't my current location and is the location I supplied via DDMS, setting the lat and long.

**Comment by feinstein** [comment]
Does this error also appear on a REAL device? Have you ever tried to test this on a real device?

Only one emulator image has Google Play Services, be sure you are using the correct one.

**Comment by sheldonhall** [comment]
You're right, it works with my S7 but what emulator does Google Pay Services work with? I tried the following:

<img width="1054" alt="screen shot 2017-11-23 at 2 35 13 pm" src="https://user-images.githubusercontent.com/5139845/33185840-ad5b104a-d05b-11e7-8636-83579b759f82.png">

**Comment by feinstein** [comment]
You have to check which ones have the Play Store check mark, like in here:

https://androidstudio.googleblog.com/2017/04/google-play-system-images-android.html?m=1

Remember, this is only valid to Android Studio 3.0

**Comment by JichunMa** [comment]
I had the same problem. Maybe I had found a solution. The problem is "com.google.android.geo.API_KEY" in your AndroidManifest.xml. The key should support  “Google Maps Android API” and "Google Places API for Android".You can check the key on the [https://console.developers.google.com/apis](url) ![avatar](http://i68.tinypic.com/ff3kg2.jpg)
 **At last thanks** @feinstein .

**Comment by feinstein** [comment]
Glad to help!

**Comment by tsriraj** [comment]
Thanks ! It helped a lot to resolve the issue.:)

**Comment by hazam** [comment]
half a day lost on this, i tried all your links all you mentioned and couldn't fix :(
Just wonder if anyone else had something else to try

**Comment by mshaileshr** [comment]
com.google.android.gms.common.api.ApiException: 16:

**Comment by reem-alhussain** [comment]
After enabling the Places API in the console, try adding the **Places SDK for Android** in the key credentials  **API Restrections** , so then you will have  **Maps SDK for Android** and  **Places SDK for Android** .
This worked for me.

**Comment by thanhlam95** [comment]
Sometimes, I have the same problem without understanding why
