### ISSUE TITLE
Failed to resolve: `com.google.android.gms:play-services-maps:11.4.0`

### ISSUE THREAD

**Issue by timegowhere** [googlemaps/android-samples#74]
Failed to resolve: `com.google.android.gms:play-services-maps:11.4.0`

**Comment by eerikk** [comment]
under your repositories you need to add         
```
maven {url "https://maven.google.com"}
```

**Comment by katherineallen** [comment]
This has been fixed in pull request #79

**Comment by WINTX** [comment]
Dont work :(

buildscript {
    repositories {
        jcenter()
        maven {url "https://maven.google.com"}
    }

**Comment by ParryPatel021** [comment]
Kindly please verify your libraries from below link and set up library versions as mentioned in the below link.
https://developers.google.com/android/guides/setup

**Comment by anuj-njoshi** [comment]
use this googlePlayServicesVisionVersion = "16.x.x" inside android/ buid.gradle
