### ISSUE TITLE
Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference

### ISSUE THREAD

**Issue by akbarmir** [googlemaps/android-samples#78]
hello for every one, i use this code (CurrentPlaceDetailsOnMap) in my app but a null exception with this title "Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference"  happens. i'm new in android and i can't solve that, please help me. (emulater api 27)

**Comment by jpb14d** [comment]
I'm having the same issue on my machine. Here's my error from LogCat:
`11-28 21:25:42.243 5763-5763/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.example.currentplacedetailsonmap, PID: 5763
                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference
                                                     at com.example.currentplacedetailsonmap.MapsActivityCurrentPlace$2.onComplete(MapsActivityCurrentPlace.java:203)
                                                     at com.google.android.gms.tasks.zzf.run(Unknown Source:23)
                                                     at android.os.Handler.handleCallback(Handler.java:790)
                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                     at android.os.Looper.loop(Looper.java:164)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`


And here is the code for the section that is throwing the error in MapsActivityCurrentPlace.java:
`   private void getDeviceLocation() {
        /*
         * Get the best and most recent location of the device, which may be null in rare
         * cases when a location is not available.
         */
        try {
            if (mLocationPermissionGranted) {
                Task<Location> locationResult = mFusedLocationProviderClient.getLastLocation();
                locationResult.addOnCompleteListener(this, new OnCompleteListener<Location>() {
                    @Override
                    public void onComplete(@NonNull Task<Location> task) {
                        if (task.isSuccessful()) {
                            // Set the map's camera position to the current location of the device.
                            mLastKnownLocation = task.getResult();
                            mMap.moveCamera(CameraUpdateFactory.newLatLngZoom(
                                    new LatLng(mLastKnownLocation.getLatitude(),
                                            mLastKnownLocation.getLongitude()), DEFAULT_ZOOM));
                        } else {
                            Log.d(TAG, "Current location is null. Using defaults.");
                            Log.e(TAG, "Exception: %s", task.getException());
                            mMap.moveCamera(CameraUpdateFactory
                                    .newLatLngZoom(mDefaultLocation, DEFAULT_ZOOM));
                            mMap.getUiSettings().setMyLocationButtonEnabled(false);
                        }
                    }
                });
            }
        } catch (SecurityException e)  {
            Log.e("Exception: %s", e.getMessage());
        }
    }`

**Comment by jpb14d** [comment]
I was able to solve this issue.
By changing the line of the code above from
`
                        if (task.isSuccessful()) {
`
to
`
                        if (task.isSuccessful() && task.getResult() != null) {
`

**Comment by KenHoang16CDTH12** [comment]
Thanks +1 @jpb14d

**Comment by Sambillings077** [comment]
private void getDeviceLocation() {

        try{
            if(mLocationPermissionGranted){
                Task<Location> locationTask=mFusedLocationProviderClient.getLastLocation();
                locationTask.addOnCompleteListener(this, new OnCompleteListener<Location>() {
                    @Override
                    public void onComplete(@NonNull Task<Location> task) {
                            if(task.isSuccessful()){
                                if(mLastKnownLocation!=null)
                                mMap.moveCamera(CameraUpdateFactory.newLatLngZoom(
                                        new LatLng(mLastKnownLocation.getLatitude(),
                                                mLastKnownLocation.getLongitude()),DEFAULT_ZOOM));
                            }else{
                                mMap.moveCamera(CameraUpdateFactory.newLatLngZoom(DEFAULT_LOCATION,DEFAULT_ZOOM));
                                mMap.getUiSettings().setMyLocationButtonEnabled(false);
                            }
                    }
                });
            }

        }catch(SecurityException e){
            Log.i(TAG,"Location not found");
        }
    }
This worked for me. I just added another nested if(mLastKnownLocation!=null) and it worked.

**Comment by Steves1996** [comment]
Quand cette methode est implemente sur une version plus evolue d'android studio comme 3.x.x elle ne donne pas il faut if(task.isSuccessful() && task.getResult() != null) ajouter ca.
Merci @jpb14d

**Comment by MohamedMohy9192** [comment]
`task.getResult()` method return  a location object so checking task.getResult if not null doesn't change the fact that is location object is null we just escape from getting app crash

**Comment by nishubharti** [comment]
and tats why m getting else part.how to solve the problem.task.get result is getting null @MohamedMohy9192

**Comment by paulaacc** [comment]
Anyone got any solutions?

**Comment by mohamedmohamedtaha** [comment]
still now, I don't find any solution

**Comment by Udesh-Kumar** [comment]
Thanx bro i solve my problem through this code.
