### ISSUE TITLE
 Could not find method google() for arguments [] on repository container.

### ISSUE THREAD

**Issue by samiujan** [googlemaps/android-samples#82]
./gradlew build

FAILURE: Build failed with an exception.

* Where:
Build file '/home/sami/android-samples2/android-samples/ApiDemos/build.gradle' line: 5

* What went wrong:
A problem occurred evaluating root project 'ApiDemos'.
> Could not find method google() for arguments [] on repository container.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.684 secs

**Comment by Leo1212** [comment]
I had the same issue.
I Fixed it by using a newer Gradle version.
old version 3.3 new version 4.5

**Comment by Escolaris** [comment]
Thanks Leo1212

**Comment by rohit75** [comment]
@Leo1212 doesn't work for me

**Comment by vishalgadhiya91** [comment]
upgrade gradle.wrapper.properties

Its working for me.

**Comment by FrogTravel** [comment]
@aeroxy Yes. But seems like sometimes gradle-wrapper.properties won't update, so do it manually, I just took it from my other project. It still didn't work though, but at least useful errors started to appear
