### ISSUE TITLE
how can i show map without google paly services?

### ISSUE THREAD

**Issue by xiaozuozi** [googlemaps/android-samples#92]

**Comment by MukeshGreenDeveloper** [comment]
google map doesnot work without play services

**Comment by xiaozuozi** [comment]
how can i Compatible with all the version of google play services when show map,because every it will show the google play services is not the latest

**Comment by xiaozuozi** [comment]
when in my app ,it says your devices does not support google play services,but in google maps app,it can show the map normal,what it cause?

**Comment by MukeshGreenDeveloper** [comment]
try this one to update ur play services
https://play.google.com/store/apps/details?id=com.weberdo.apps.serviceinfo

**Comment by xiaozuozi** [comment]
why google maps app do not need google play services?because it is there own?

**Comment by xiaozuozi** [comment]
why google maps app do not need google play services?because it is their own?

**Comment by xiaozuozi** [comment]
where is the google play services in google play store,i can not find it

**Comment by MukeshGreenDeveloper** [comment]
https://play.google.com/store/apps/details?id=com.google.android.gms&hl=en
