### ISSUE TITLE
'getGeoDataClient(android.app.Activity, com.google.android.gms.location.places.PlacesOptions)' is deprecated less

### ISSUE THREAD

**Issue by alaadeego** [googlemaps/android-samples#95]
getGeoDataClient  , getPlaceDetectionClient,  is deprecated how to solve it
 my Gradle version is 4.1
any help..?

**Comment by Rawan-Eltobgy** [comment]
https://developers.google.com/android/reference/com/google/android/gms/location/places/Places
As the docs state:
-"getGeoDataClient", This method was deprecated.
use getGeoDataClient(Context) instead.
-"getPlaceDetectionClient", This method was deprecated.
use getPlaceDetectionClient(Context) instead

**Comment by barry-schneider** [comment]
The[ google example](https://github.com/googlesamples/android-play-places/blob/master/PlaceCompleteAdapter/Application/src/main/java/com/example/google/playservices/placecomplete/MainActivity.java) uses the wrong signature:

       // Construct a GeoDataClient for the Google Places API for Android.
        mGeoDataClient = Places.getGeoDataClient(this, null);

Use this instead

         mGeoDataClient = Places.getGeoDataClient(this);
