### ISSUE TITLE
A question for the Demo

### ISSUE THREAD

**Issue by 24suixinsuoyu** [googlemaps/android-samples#958]
What's the differences between gsm and v3?

**Comment by wangela** [comment]
v3 should have been named v3-beta. That folder demonstrates use of the now-deprecated [standalone v3 SDK beta](https://developers.google.com/maps/documentation/android-sdk/v310-beta).

You should use the demos under `/gms` which stands for [Google Mobile Services](https://www.android.com/gms/), where the generally available version of the Maps SDK for Android is available.
