### ISSUE TITLE
Google Map V2 Want Support Language

### ISSUE THREAD

**Issue by SunryTeang** [googlemaps/android-samples#96]
![screencapturer snapshot 2018-04-20 16 12 45](https://user-images.githubusercontent.com/31978534/39042747-d28d659c-44b5-11e8-99eb-fa61e0e81dc2.png)
i want to SupportMapFragment can be render my Cambodia Language
how can i do.
but in google map in playstore it can be render 
may you give some document for develope android app?

Thank you...

**Comment by amuramoto** [comment]
see https://developers.google.com/maps/documentation/android-sdk/map#localize_your_map
