### ISSUE TITLE
Map is not shown

### ISSUE THREAD

**Issue by alexd555** [googlemaps/android-samples#99]
Hi,

I try to run this example and map with location is not shown.
I have samsung galaxsy 5 and 6.0.1 OS

Could you help ?

Thanks,
Alex

**Comment by DvlopRyanSpears** [comment]
i've face the same problem as Alex

**Comment by DvlopRyanSpears** [comment]
Hi，Alex 
There is the solution：
You need to replace with your own API key in the AndroidManifest.

**Comment by DvlopRyanSpears** [comment]
@alexd555

**Comment by jessandroid** [comment]
@DvlopRyanSpears have you solution this question

**Comment by DvlopRyanSpears** [comment]
@jessandroid  Yes.

**Comment by DvlopRyanSpears** [comment]
@jessandroid  I just solve my own problem, just because the API key is missing.
And i'm not sure Alex has face the same problem with me, As he didn't  reply me.

**Comment by jessandroid** [comment]
@DvlopRyanSpears Google Maps not Showing in Samsung S8 but other devices is normal .

**Comment by Lavanyarohilla1996** [comment]
Even after giving our API key, the app is crashing unexpectedly.

**Comment by mecoFarid** [comment]
You can't use your key for this project. Either you have to generate API key for this project (if not generated by someone) or they should push the key as well to make this project useful
